version: 0.0
os: linux
files:
  - source: /html_project_zip
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/restart_nginx.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      runas: root
